[WIP] Added image uploading in authoring mode [#178284894]
concord-consortium/question-interactives pull request #112
Opened 2021-07-02 19:56 UTC by dougmartin

https://github.com/concord-consortium/lara/pull/724

2021-07-02 20:07 UTC, dougmartin commented
@scytacki See the PR description for detailed info.

This works locally with an `npm link` to the latest token-service and another `npm link` to the Lara PR referenced in the PR message.  Lara needed to be updated to enable `getFirebaseJWT` in authoring mode and the token-service 2.0 hasn't been published yet (I didn't want to go ahead and publish it in case there was a reason why it wasn't published).

2021-07-20 20:08 UTC, scytacki commented
@dougmartin did you test adding an image uploading interactive inside of a carousel and inside of a scaffolded question? 

These 'nesting' interactives need to proxy postMessage requests. It looks like they are not proxying the getFirebaseJwt messages. So I'm guessing that if you embed an interactive that has an image uploading field inside of them, it won't work.

2021-07-20 20:21 UTC, dougmartin commented
@scytacki I missed the proxying bit.  The code gracefully fails when it can't get a JWT so I didn't notice when manually testing.  I'll add it now.

2021-07-20 20:35 UTC, scytacki requested changes
This looks good. 

The only issue I found was the proxying in the carousel and scaffolded question. 

Perhaps it can be taken out of Draft now that the token-service and interactive-api are released.

2021-07-21 08:11 UTC, dougmartin commented
@scytacki I've added the proxying of the firebase JWT in this commit https://github.com/concord-consortium/question-interactives/pull/112/commits/88909bc90bacb4aa038140efe38bf49e0298d0e3

This took way longer than I thought it would as I was missing the `requestId` in the proxied response so it was getting dropped by the Lara client.

2021-07-21 19:40 UTC, scytacki approved these changes
Looks good to me.

2021-07-21 19:41 UTC, merged