182721195 save side-by-side interactive state on nav
concord-consortium/question-interactives pull request #375
Opened 2024-05-03 18:06 UTC by eireland

2024-05-06 11:38 UTC, pjanik reviewed
Generally looks good, especially if it fixes the bug. :)

Out of curiosity, do we understand why the ref had to be used there? What was happening without it? 

I'm asking because we're touching a pretty critical part of the question interaction and answer saving. It would be nice to understand that completely. Otherwise, we might accidentally break the saving of answers in some edge cases. Perhaps @dougmartin should double-check that, as I guess Doug is more familiar with the whole onUnloadCallbackRef and resolveOnUnload logic.

2024-05-06 11:52 UTC, dougmartin requested changes
Looks good overall :+1:  I'm really surprised we didn't catch the `onUnloadCallback` being bound inside the interactive state listener.  We need to smoke test this change with all the interactives in QA to ensure this doesn't break them.

Could you change the check for the `onUnloadCallbackRef` as mentioned in the comments?  I think it will make this easier to understand for someone in the future.

2024-05-06 11:52 UTC, dougmartin commented on packages/helpers/src/components/iframe-runtime.tsx
> +        if (onUnloadCallbackRef?.current && resolveOnUnload.current) {
I think you can change this to `onUnloadCallbackRef.current` as the current value is always set on line 56 (the current value may be undefined but the ref is always defined).

2024-05-06 11:52 UTC, dougmartin commented on packages/helpers/src/components/iframe-runtime.tsx
> +          onUnloadCallbackRef?.current(newInteractiveState);
Same comment as above, should be `onUnloadCallbackRef.current`.

2024-05-07 09:44 UTC, dougmartin approved these changes
Changes look good :+1:

2024-05-07 17:20 UTC, merged